<?xml version="1.0" encoding="utf-8"?><Database Name="ERPManagement" Class="ERPManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ERPManagement;Integrated Security=True" SettingsObjectName="ERPManagement.Properties.Settings" SettingsPropertyName="ERPManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Company_Department" Member="Departments" ThisKey="CompanyID" OtherKey="CompanyID" Type="Department" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Employee" />
      <Association Name="Department_EquipmentHandOver" Member="EquipmentHandOvers" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="EquipmentHandOver" />
      <Association Name="Company_Department" Member="Company" ThisKey="CompanyID" OtherKey="CompanyID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnitMeasure" Member="UnitMeasures">
    <Type Name="UnitMeasure">
      <Column Name="UnitMeasureID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="UnitMeasure_Equipment" Member="Equipments" ThisKey="UnitMeasureID" OtherKey="UnitMeasureID" Type="Equipment" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="PermissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MethodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CanRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanWrite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Method_Permission" Member="Method" ThisKey="MethodID" OtherKey="MethodID" Type="Method" IsForeignKey="true" />
      <Association Name="Employee_Permission" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Method" Member="Methods">
    <Type Name="Method">
      <Column Name="MethodID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Method_Permission" Member="Permissions" ThisKey="MethodID" OtherKey="MethodID" Type="Permission" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentType" Member="EquipmentTypes">
    <Type Name="EquipmentType">
      <Column Name="EquipmentTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="EquipmentType_Equipment" Member="Equipments" ThisKey="EquipmentTypeID" OtherKey="EquipmentTypeID" Type="Equipment" />
    </Type>
  </Table>
  <Table Name="dbo.Equipment" Member="Equipments">
    <Type Name="Equipment">
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitMeasureID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Association Name="Equipment_EquipmentImportationDetail" Member="EquipmentImportationDetails" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="EquipmentImportationDetail" />
      <Association Name="Equipment_EquipmentExportationDetail" Member="EquipmentExportationDetails" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="EquipmentExportationDetail" />
      <Association Name="Equipment_EquipmentHandOverDetail" Member="EquipmentHandOverDetails" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="EquipmentHandOverDetail" />
      <Association Name="EquipmentType_Equipment" Member="EquipmentType" ThisKey="EquipmentTypeID" OtherKey="EquipmentTypeID" Type="EquipmentType" IsForeignKey="true" />
      <Association Name="UnitMeasure_Equipment" Member="UnitMeasure" ThisKey="UnitMeasureID" OtherKey="UnitMeasureID" Type="UnitMeasure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentImportationDetail" Member="EquipmentImportationDetails">
    <Type Name="EquipmentImportationDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RestQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Equipment_EquipmentImportationDetail" Member="Equipment" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="Equipment" IsForeignKey="true" />
      <Association Name="EquipmentImportation_EquipmentImportationDetail" Member="EquipmentImportation" ThisKey="ID" OtherKey="ID" Type="EquipmentImportation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentImportation" Member="EquipmentImportations">
    <Type Name="EquipmentImportation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Deliver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentImportation_EquipmentImportationDetail" Member="EquipmentImportationDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentImportationDetail" />
      <Association Name="Employee_EquipmentImportation" Member="Employee" ThisKey="Deliver" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentExportation" Member="EquipmentExportations">
    <Type Name="EquipmentExportation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Receiver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentExportation_EquipmentExportationDetail" Member="EquipmentExportationDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentExportationDetail" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentExportationDetail" Member="EquipmentExportationDetails">
    <Type Name="EquipmentExportationDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RestQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Equipment_EquipmentExportationDetail" Member="Equipment" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="Equipment" IsForeignKey="true" />
      <Association Name="EquipmentExportation_EquipmentExportationDetail" Member="EquipmentExportation" ThisKey="ID" OtherKey="ID" Type="EquipmentExportation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Regency" Member="Regencies">
    <Type Name="Regency">
      <Column Name="RegencyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Regency_Employee" Member="Employees" ThisKey="RegencyID" OtherKey="RegencyID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.WareHouse" Member="WareHouses">
    <Type Name="WareHouse">
      <Column Name="WareHouseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentBreak" Member="EquipmentBreaks">
    <Type Name="EquipmentBreak">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Advise" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Assignment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Repairer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecvInfoDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RepairDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="EquipmentBreak_EquipmentBreakDetail" Member="EquipmentBreakDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentBreakDetail" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentBreakDetail" Member="EquipmentBreakDetails">
    <Type Name="EquipmentBreakDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Advise" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Association Name="EquipmentBreak_EquipmentBreakDetail" Member="EquipmentBreak" ThisKey="ID" OtherKey="ID" Type="EquipmentBreak" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FamilyName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BirthPlace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ethnic" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RegencyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_Permission" Member="Permissions" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Permission" />
      <Association Name="Employee_EquipmentImportation" Member="EquipmentImportations" ThisKey="EmployeeID" OtherKey="Deliver" Type="EquipmentImportation" />
      <Association Name="Employee_EquipmentHandOverReceiver" Member="EquipmentHandOverReceivers" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EquipmentHandOverReceiver" />
      <Association Name="Employee_EquipmentHandOverSender" Member="EquipmentHandOverSenders" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EquipmentHandOverSender" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="Regency_Employee" Member="Regency" ThisKey="RegencyID" OtherKey="RegencyID" Type="Regency" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentHandOverDetail" Member="EquipmentHandOverDetails">
    <Type Name="EquipmentHandOverDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Equipment_EquipmentHandOverDetail" Member="Equipment" ThisKey="EquipmentID" OtherKey="EquipmentID" Type="Equipment" IsForeignKey="true" />
      <Association Name="EquipmentHandOver_EquipmentHandOverDetail" Member="EquipmentHandOver" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOver" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentHandOverReceiver" Member="EquipmentHandOverReceivers">
    <Type Name="EquipmentHandOverReceiver">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EquipmentHandOverReceiver" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="EquipmentHandOver_EquipmentHandOverReceiver" Member="EquipmentHandOver" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOver" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentHandOverSender" Member="EquipmentHandOverSenders">
    <Type Name="EquipmentHandOverSender">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EquipmentHandOverSender" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="EquipmentHandOver_EquipmentHandOverSender" Member="EquipmentHandOver" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOver" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentHandOver" Member="EquipmentHandOvers">
    <Type Name="EquipmentHandOver">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentHandOver_EquipmentHandOverDetail" Member="EquipmentHandOverDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOverDetail" />
      <Association Name="EquipmentHandOver_EquipmentHandOverReceiver" Member="EquipmentHandOverReceivers" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOverReceiver" />
      <Association Name="EquipmentHandOver_EquipmentHandOverSender" Member="EquipmentHandOverSenders" ThisKey="ID" OtherKey="ID" Type="EquipmentHandOverSender" />
      <Association Name="Department_EquipmentHandOver" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentStatusNoteBook" Member="EquipmentStatusNoteBooks">
    <Type Name="EquipmentStatusNoteBook">
      <Column Name="NoteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentStatusNoteBook_EquipmentStatusNoteBookDetail" Member="EquipmentStatusNoteBookDetails" ThisKey="NoteID" OtherKey="ID" Type="EquipmentStatusNoteBookDetail" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentStatusNoteBookDetail" Member="EquipmentStatusNoteBookDetails">
    <Type Name="EquipmentStatusNoteBookDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cause" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="EquipmentStatusNoteBook_EquipmentStatusNoteBookDetail" Member="EquipmentStatusNoteBook" ThisKey="ID" OtherKey="NoteID" Type="EquipmentStatusNoteBook" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentReturning" Member="EquipmentReturnings">
    <Type Name="EquipmentReturning">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentReturning_EquipmentReturningReceiver" Member="EquipmentReturningReceivers" ThisKey="ID" OtherKey="ID" Type="EquipmentReturningReceiver" />
      <Association Name="EquipmentReturning_EquipmentReturningSender" Member="EquipmentReturningSenders" ThisKey="ID" OtherKey="ID" Type="EquipmentReturningSender" />
      <Association Name="EquipmentReturning_EquipmentReturningDetail" Member="EquipmentReturningDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentReturningDetail" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentReturningReceiver" Member="EquipmentReturningReceivers">
    <Type Name="EquipmentReturningReceiver">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentReturning_EquipmentReturningReceiver" Member="EquipmentReturning" ThisKey="ID" OtherKey="ID" Type="EquipmentReturning" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentReturningSender" Member="EquipmentReturningSenders">
    <Type Name="EquipmentReturningSender">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentReturning_EquipmentReturningSender" Member="EquipmentReturning" ThisKey="ID" OtherKey="ID" Type="EquipmentReturning" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentReturningDetail" Member="EquipmentReturningDetails">
    <Type Name="EquipmentReturningDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentReturning_EquipmentReturningDetail" Member="EquipmentReturning" ThisKey="ID" OtherKey="ID" Type="EquipmentReturning" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentTransfer" Member="EquipmentTransfers">
    <Type Name="EquipmentTransfer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Association Name="EquipmentTransfer_EquipmentTransferDetail" Member="EquipmentTransferDetails" ThisKey="ID" OtherKey="ID" Type="EquipmentTransferDetail" />
      <Association Name="EquipmentTransfer_EquipmentTransferReceiver" Member="EquipmentTransferReceivers" ThisKey="ID" OtherKey="ID" Type="EquipmentTransferReceiver" />
      <Association Name="EquipmentTransfer_EquipmentTransferSender" Member="EquipmentTransferSenders" ThisKey="ID" OtherKey="ID" Type="EquipmentTransferSender" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentTransferDetail" Member="EquipmentTransferDetails">
    <Type Name="EquipmentTransferDetail">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EquipmentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="EquipmentTransfer_EquipmentTransferDetail" Member="EquipmentTransfer" ThisKey="ID" OtherKey="ID" Type="EquipmentTransfer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentTransferReceiver" Member="EquipmentTransferReceivers">
    <Type Name="EquipmentTransferReceiver">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentTransfer_EquipmentTransferReceiver" Member="EquipmentTransfer" ThisKey="ID" OtherKey="ID" Type="EquipmentTransfer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EquipmentTransferSender" Member="EquipmentTransferSenders">
    <Type Name="EquipmentTransferSender">
      <Column Name="DetailID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Index]" Member="Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EquipmentTransfer_EquipmentTransferSender" Member="EquipmentTransfer" ThisKey="ID" OtherKey="ID" Type="EquipmentTransfer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>